# Enable the H2 Console
spring.h2.console.enabled=true

# Fixed URL to make logging in easier
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=