spring.application.name=springsecurity
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
security.jwt.secret=emV0YS1kaWdpdGFsLWZkLXNlY3JldC1rZXktMTIzNDU2Nzg5MA==
security.jwt.expiration-ms=3600000
security.refesh-token.expiration-ms=86400000