spring.application.name=springsecurity

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/springsecuritydb
spring.datasource.username=postgres
spring.datasource.password=Pandey@2683
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable H2 console (not needed anymore)
spring.h2.console.enabled=false

# JWT Configuration
security.jwt.secret=emV0YS1kaWdpdGFsLWZkLXNlY3JldC1rZXktMTIzNDU2Nzg5MA==
security.jwt.expiration-ms=3600000
security.refresh-token.expiration-ms=86400000