spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:docker_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Pandey@2683}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true