spring.application.name=transaction

# Basic PostgreSQL datasource configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/TDEMO}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Pandey@2683}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA defaults for local development
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

